sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
rvm:
  - 2.4.2
services:
  - postgresql
  - memcached
  - redis-server
addons:
  postgresql: "9.6"
  apt:
    sources:
      - sourceline: 'ppa:maxmind/ppa'
    packages:
      - libmaxminddb0
      - libmaxminddb-dev
      - mmdb-bin
before_install:
  - nvm install 8.6
  - nvm use 8.6
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - openssl aes-256-cbc -K $encrypted_daa687493782_key -iv $encrypted_daa687493782_iv -in ci/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
before_script:
  - npm rebuild node-sass
  - psql -c 'create database drfvote_test;' -U postgres
script:
  - DISABLE_SPRING=1 bundle exec rake assets:precompile
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec rake test
