language: ruby
cache: bundler
rvm:
  - 2.4.1
services:
  - postgresql
  - memcached
  - redis-server
addons:
  postgresql: "9.6"
script:
  - RAILS_ENV=test bundle exec rake assets:precompile
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rspec
  - RAILS_ENV=test bundle exec rake test
before_script:
  - psql -c 'create database drfvote_test;' -U postgres
